### ISSUE TITLE
构建出来的镜像执行命令的时候有点问题

### ISSUE THREAD

**Issue by lz-xinlin** [CodingOX/awasome-dockerfile#1]
![image](https://user-images.githubusercontent.com/38177686/222072920-1e24b55f-eaf4-4dca-a0d6-c417e5c51f1c.png)

**Comment by CodingOX** [comment]
> ![image](https://user-images.githubusercontent.com/38177686/222072920-1e24b55f-eaf4-4dca-a0d6-c417e5c51f1c.png)

抱歉 这个已经很久没有维护了 所以没有继续提供更多有用信息了
目前我们使用的是`temurin-jdk 11` 可以参考下是否能用: `eclipse-temurin:11.0.17_8-jdk-centos7` 该项目也有jdk8的版本,[链接地址](https://hub.docker.com/_/eclipse-temurin/tags)

**Comment by lz-xinlin** [comment]
谢谢
